[package]
name = "torb-cli"
description = "The torb command line tool"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "torb"
path = "src/main.rs"

[dependencies]
torb-syntax = { path = "../torb-syntax" }
torb-interpreter = { path = "../torb-interpreter" }

[lints]
workspace = true
